### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by blackbeario** [strongloop/loopback-connector-soap#105]
I am getting a stack size error while using the CLI `lb soap` command, while trying to access my OMS web services. My lb common models have already been created via the mssql connector, if that matters at all. The OMS can be viewed at https://smapromail.cgraphics.com/pmomsws/oms.asmx?WSDL.

```events.js:167
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at Array.indexOf (<anonymous>)
    at checkAndConvertToNumber (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:438:25)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:321:13)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
    at buildElementProperties (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-soap/lib/codegen/generator-soap.js:327:7)
Emitted 'error' event at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/yeoman-generator/lib/base.js:446:16)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

# Additional information

darwin x64 10.3.0

├── loopback@3.20.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.0.1
├── loopback-component-storage@3.3.1
├── loopback-connector-mongodb@3.4.4
├── loopback-connector-mssql@2.9.0
├── loopback-connector-soap@5.0.0
├── loopback-ds-timestamp-mixin@3.4.1

**Comment by pythlang** [comment]
I also just got the same thing, but I think it's because of a function defined in the WSDL. I was able to use this no problem with a different WSDL. I will look into it a bit.

**Comment by JoseMontesRicardo** [comment]
I also just got the same thing

**Comment by Juanpaie** [comment]
Same issue here, any ideas?
