### ISSUE TITLE
node-soap 0.9.4 doesn't work

### ISSUE THREAD

**Issue by Juneil** [strongloop/loopback-connector-soap#25]
Hi, 
The new release from node-soap is not working with loopback-connector-soap
Can you temporarily fixed the version to 0.9.3 ?

Thanks,

**Comment by raymondfeng** [comment]
What problems do you see?

**Comment by Juneil** [comment]
TypeError: undefined is not a function
    at LBHttpClient.request (/********/node_modules/loopback-connector-soap/lib/http.js:94:18)
    at open_wsdl (/********/node_modules/loopback-connector-soap/node_modules/soap/lib/wsdl.js:1903:16)
    at _requestWSDL (/********/node_modules/loopback-connector-soap/node_modules/soap/lib/soap.js:32:5)
    at Object.createClient (/********/node_modules/loopback-connector-soap/node_modules/soap/lib/soap.js:49:3)
    at SOAPConnector.connect (/********/node_modules/loopback-connector-soap/lib/soap-connector.js:60:8)
    at Object.initializeDataSource [as initialize] (/********/node_modules/loopback-connector-soap/lib/soap-connector.js:18:13)
    at DataSource.setup (/********/node_modules/loopback-datasource-juggler/lib/datasource.js:332:17)
    at new DataSource (/********/node_modules/loopback-datasource-juggler/lib/datasource.js:109:8)
    at Registry.createDataSource (/********/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/********/node_modules/loopback/lib/application.js:414:19)

**Comment by raymondfeng** [comment]
Fixed in ver 2.1.0
