### ISSUE TITLE
Error: Could not find package.json up from: /

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-soap#27]
Getting the following error trying to run this module behind Passenger Nginx after upgrading to the latest version:

/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:22
    throw new Error('Could not find package.json up from: ' + dir);
          ^
Error: Could not find package.json up from: /
    at find (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:22:11)
    at find (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:27:10)
    at find (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:27:10)
    at find (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:27:10)
    at find (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:27:10)
    at readRootPackage (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/lib/approot.js:31:13)
    at Object.<anonymous> (/home/app/node_modules/loopback-connector-soap/node_modules/strongloop-license/index.js:14:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/app/node_modules/loopback-connector-soap/index.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by gunjpan** [comment]
Closing as license requirement is already removed in the current version of this connector.
