### ISSUE TITLE
AssertionError: setRootDir: Intl dir not found under

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-soap#54]
```
> require('loopback-connector-soap')
AssertionError: *** setRootDir: Intl dir not found under: /Users/rfeng/Demos/d1/node_modules/loopback-connector-soap
    at Object.setRootDir (/Users/rfeng/Demos/d1/node_modules/strong-globalize/lib/helper.js:153:3)
    at Function.SetRootDir (/Users/rfeng/Demos/d1/node_modules/strong-globalize/index.js:48:13)
    at Object.<anonymous> (/Users/rfeng/Demos/d1/node_modules/loopback-connector-soap/index.js:7:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-connector-soap/pull/52
