### ISSUE TITLE
The `ModelDefinition` instance is not valid; `name` is invalid

### ISSUE THREAD

**Issue by adamski** [strongloop/loopback-connector-soap#78]
I am getting an error generating from the following WSDL: https://access.uat.oup.com/eacWebService/services/access-service-v2.0.wsdl

```
Creating model definition for soap_access-service-v2.0Soap11...
Creating model definition for ValidatePasswordCredentialsRequest...
Creating model definition for PasswordCredential...
Creating model definition for ValidatePasswordCredentialsResponse...
Creating model definition for GetFullUserEntitlementsRequest...
Creating model definition for wsUserId...
Creating model definition for Identifier...
Creating model definition for InternalIdentifier...
Creating model definition for ExternalIdentifier...
Creating model definition for GetFullUserEntitlementsResponse...
Creating model definition for ErrorStatus...
Updating model definition for User...
Creating model definition for Identifiers...
Creating model definition for FullProductEntitlementGroup...
Creating model definition for FullProductEntitlement...
Creating model definition for FullProductDetails...
Creating model definition for LicenceDetails...
Creating model definition for ExtendedLicenceDetails...
Creating model definition for RollingLicenceDetail...
Creating model definition for ConcurrencyLicenceDetails...
Creating model definition for UsageLicenceDetails...
Creating model definition for LicenceInfo...
Creating model definition for AuthenticateRequest...
Creating model definition for Credential...
Creating model definition for IPCredential...
Creating model definition for AuthenticateResponse...
Creating model definition for CreateUserAccountRequest...
Creating model definition for CreateUser...
Creating model definition for CreateUserAccountResponse...
Creating model definition for userStatusType...
Creating model definition for UpdateUserAccountRequest...
Creating model definition for UpdateUser...
Creating model definition for UpdateUserAccountResponse...
Validation error: invalid ModelDefinition
 - name: is invalid

events.js:163
      throw er; // Unhandled 'error' event
      ^
ValidationError: The `ModelDefinition` instance is not valid. Details: `name` is invalid (value: "soap_access-service-v2.0Soap11").
 
```

Any clues? Thanks

**Comment by rashmihunt** [comment]
Fixed with above PRs. Closing.  Try with the latest https://www.npmjs.com/package/loopback-cli

**Comment by artyomboyko** [comment]
Have the same issue
```
Creating model definition for GetAddressesByUcdmIdResponse...
Creating model definition for AddressPaging...
Validation error: invalid ModelDefinition
 - name: is invalid

events.js:160
      throw er; // Unhandled 'error' event
      ^
ValidationError: The `ModelDefinition` instance is not valid. Details: `name` is invalid (value: "AddressInfo.AddressValida...nfo").
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:330:12
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:511:13)
    at ModelConstructor.next (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/hooks.js:82:12)
    at done (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:508:25)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:586:7
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:380:5)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:2009:11
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at async.each (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at _asyncMap (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
    at Object.map (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)
    at allCb (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:1937:15)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:508:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by artyomboyko** [comment]
```
Creating model definition for AddressPaging...
Validation error: invalid ModelDefinition
 - name: is invalid

events.js:160
      throw er; // Unhandled 'error' event
      ^
ValidationError: The `ModelDefinition` instance is not valid. Details: `name` is invalid (value: "AddressInfo.AddressValida...nfo").
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:330:12
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:511:13)
    at ModelConstructor.next (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/hooks.js:82:12)
    at done (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:508:25)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:586:7
    at ModelConstructor.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/validations.js:380:5)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:2009:11
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at async.each (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at _asyncMap (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:390:13)
    at Object.map (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:361:23)
    at allCb (/usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/dao.js:1937:15)
    at /usr/local/lib/node_modules/loopback-cli/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:508:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
